
version: '3.8'
services:
  transactionservicedb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33306:3306'
    volumes:
      - transactionservicedb:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  transactionservicedb:
    driver: local
