CREATE TABLE IF NOT EXISTS accountbalance(
   id INT AUTO_INCREMENT PRIMARY KEY,
   accountno VARCHAR(100) NOT NULL,
   balance DECIMAL(20,5) NOT NULL,
   doneby VARCHAR(100) DEFAULT 'I' NOT NULL,
   uptime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE(accountno)
);
