CREATE TABLE IF NOT EXISTS account(
   id INT AUTO_INCREMENT PRIMARY KEY,
   accountno VARCHAR(100) NOT NULL,
   name VARCHAR(1000) NOT NULL,
   uptime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE(accountno)
);
