CREATE TABLE IF NOT EXISTS accountloginsession(
   id INT AUTO_INCREMENT PRIMARY KEY,
   sessionkey VARCHAR(100) NOT NULL,
   accountno VARCHAR(100) NOT NULL,
   expirytime TIMESTAMP NOT NULL,
   uptime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE(sessionkey)
);
