CREATE TABLE IF NOT EXISTS accountsync(
   id INT AUTO_INCREMENT PRIMARY KEY,
   msgkey VARCHAR(100) NOT NULL,
   accountno VARCHAR(100) NOT NULL,
   payload VARCHAR(1000) NOT NULL,
   status CHAR(1) NOT NULL,
   uptime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE(msgkey)
);
